services:
  statsd-exporter:
    image: prom/statsd-exporter
    container_name: statsd-exporter
    ports:
      - "9125:9125/udp"  # Serf nodes send metrics here
      - "9102:9102"      # Prometheus scrapes metrics from this port
    networks:
      - serf-monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - serf-monitoring
    depends_on:
      - statsd-exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin   # Set default admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set default admin password
    networks:
      - serf-monitoring
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  serf-monitoring:
    driver: bridge
